# Generated by Django 5.0.6 on 2024-06-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_rename_genre_songgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='songs.songgenre'),
        ),
    ]
