# Generated by Django 5.0.6 on 2024-06-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_alter_songmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='songgenre',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=35, unique=True),
        ),
    ]
