# Generated by Django 5.0.6 on 2024-06-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_songgenre_slug_songmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgenre',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
