# Generated by Django 5.0.6 on 2024-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_alter_songgenre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgenre',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=35),
        ),
    ]
