# Generated by Django 5.0.6 on 2024-06-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_usercabinet_slug'),
        ('songs', '0010_alter_songgenre_slug_alter_songmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='author_nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.usercabinet'),
        ),
    ]
