# Generated by Django 5.0.6 on 2024-06-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_songmodel_author_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='song_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='название'),
        ),
    ]
