# Generated by Django 5.0.6 on 2024-06-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('songs', '0012_alter_songmodel_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='songs.songmodel'),
            preserve_default=False,
        ),
    ]
