# Generated by Django 5.0.6 on 2024-06-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercabinet',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
