# Generated by Django 5.0.6 on 2024-06-20 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_usercabinet_slug'),
        ('songs', '0008_songgenre_slug_songmodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cabinet', to=settings.AUTH_USER_MODEL, verbose_name='пользаватель'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='favorite_genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.songgenre', verbose_name='любимый жанр'),
        ),
    ]
