# Generated by Django 5.0.6 on 2024-06-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_alter_usercabinet_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
